##################################################################
# VS Code with REST Client extension is needed to use this file.
# Download at: https://aka.ms/vscode/rest-client
##################################################################

# Completion without streaming
curl -X POST http://localhost:4041/openai/deployments/test/completions \
  -H "Content-Type: application/json" \
  -d '{ "prompt": "Once upon a time", "max_tokens": 20 }'

###

# Completion with streaming
curl -X POST http://localhost:4041/openai/deployments/test/completions \
  -H "Content-Type: application/json" \
  -d '{ "prompt": "Once upon a time", "max_tokens": 20, "stream": true }'

###

# Use deployment as model name (use `ollamazure -d`)
curl -X POST http://localhost:4041/openai/deployments/mistral:v0.2/completions \
  -H "Content-Type: application/json" \
  -d '{ "prompt": "Once upon a time", "max_tokens": 20 }'

###

# Reproducible output
curl -X POST http://localhost:4041/openai/deployments/test/completions \
  -H "Content-Type: application/json" \
  -d '{ "prompt": "Once upon a time", "max_tokens": 20, "seed": 42 }'

###

# Chat completion without streaming
curl -X POST http://localhost:4041/openai/deployments/test/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Say hello in French, Japanese, and Spanish."
      }
    ]
  }'

###

# Chat completions with streaming
curl -X POST http://localhost:4041/openai/deployments/test/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Say hello in French, Japanese, and Spanish."
      }
    ],
    "stream": true
  }'

###

# JSON mode
curl -X POST http://localhost:4041/openai/deployments/test/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Say hello in French, Japanese, and Spanish. Answer with JSON only."
      }
    ],
    "response_format": { "type": "json_object" }
  }'

###

# Embeddings
curl -X POST http://localhost:4041/openai/deployments/test/embeddings \
  -H "Content-Type: application/json" \
  -d '{ "input": "Once upon a time" }'

###

# Embeddings multiple documents
curl -X POST http://localhost:4041/openai/deployments/test/embeddings \
  -H "Content-Type: application/json" \
  -d '{ "input": ["Once upon a time", "The end."] }'

###

# Embeddings as base64
curl -X POST http://localhost:4041/openai/deployments/test/embeddings \
  -H "Content-Type: application/json" \
  -d '{ "input": "Once upon a time", "encoding_format": "base64"}'

###

# Embeddings with token input
curl -X POST http://localhost:4041/openai/deployments/test/embeddings \
  -H "Content-Type: application/json" \
  -d '{ "input": [ 12805, 5304, 264, 892 ] }'
